### ISSUE TITLE
Fix Starring and Unstarring

### ISSUE THREAD

**Issue by zenware** [eleweek/histsync#12]
First I came here to leave an issue about maybe allowing commands to be upvoted which I thought would be cool, and then I realized that Starring other peoples commands acts in the same way as an upvote would.

So the issue is twofold, one is that when you star something a message pops over and says you starred it, but the counter doesn't increment without refreshing the page. And the second part of the issue is that unstar does not work entirely.

I will probably submit a pull request to fix this sometime tomorrow if you don't mind. Otherwise it's probably not difficult to fix yourself.

**Comment by eleweek** [comment]
Yeah, I forgot about incrementing/decrementing the counter.

I think `current_user.remove(c)` should actually be `current_user.commands.remove(c)`

**Comment by eleweek** [comment]
Also, I don't mind a pull-request at all! I'll be happy to merge it

**Comment by zenware** [comment]
It looks like it's added with `current_user.starred_commands.append(c)`
I'm not actually sure how to force `{{stars_number}}` to update though. I will read the docs and get back.

**Comment by eleweek** [comment]
@zenware I think simply incrementing it(using ajax) without making a request to the server would suffice. 

Making a request to the server is an option, but it requires an api(which isn't available right now)

**Comment by zenware** [comment]
/me tries to help develop a flask application knowing nothing about flask.
I'm reading about how the templating and macro stuff works right now.

**Comment by eleweek** [comment]
ok! But you don't really need to use macros here and you can simply update it using ajax(ui.js file)

**Comment by zenware** [comment]
What!, that's amazing

**Comment by eleweek** [comment]
Basically, templates are rendered on server-side(not client side), so clients have full html. While things are {{stars_number}} are used in templates on server-side, you can simply increment the number using plain ajax
