### ISSUE TITLE
install.bash: automaticly add lines to end of .bashrc / .bash_profiles

### ISSUE THREAD

**Issue by PhillipSz** [eleweek/histsync#31]
I mean the user must trust you anyway if he/she runs "crul | bash". 
So I see no problem with just adding it. What do you think?
Maybe we could just ask, if the user wants to use .bashrc (most will use this) or .bash_profiles?

**Comment by eleweek** [comment]
I thought about adding it automatically, but I worry this may result in some unexpected results. 

> Maybe we could just ask

I think this is a good idea. After it prints "Add the following lines" <lines> we could ask "Would you like to automatically add these lines to the end of your .bashrc / .bash_profile". 

I'm not sure if I have time to implement this, but if you're willing to work on, I'll be happy to merge your pull-request!

**Comment by eleweek** [comment]
Thanks! I'm closing this issue because your awesome pull-request was merged
